# =====================================================
# Website Configuration
# This section contains general information about your website.
# =====================================================

site:
  name: "Pin-Yen"
  repoUrl: "https://github.com/pm25/pm25.github.io"
  description: "Pin-Yen's personal website"
  author: "Pin-Yen Huang"
